version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cinema-postgres
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
    volumes:
      - cinema_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: cinema-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cinema_db
      SPRING_DATASOURCE_USERNAME: cinema_user
      SPRING_DATASOURCE_PASSWORD: cinema_pass

volumes:
  cinema_pg_data:
