version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cinema-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
    volumes:
      - cinema_pg_data:/var/lib/postgresql/data

volumes:
  cinema_pg_data:
